lessons.json
I changed Lessons to Chapter for the translation, a literal German translation would've sounded a little awkward
=> Added German for common_words

README.md, lessons.yaml
Translations for:
- Welcome page
- Chapter 1 - The Basics
- The Rust Playground
Added contributor
=> Spanish(Spain) translations

lessons.yaml
Hey all, I realized that I forgot a rather important page in the first chapter. I'll keep this page in beta until you all have time to translate.
@jassler @Dhghomon @knightpp @albatraduce
=> need to add page on returning nothing

lessons.yaml
it's -> its
flexability -> flexibility
a enum -> an enum
=> Minor English fixes

lessons.yaml
=> add russian for chapter 3

lessons.yaml
Hey all, this page has been bothering me for awhile. :) Sorry to rewrite it.
=> rewriting this page on exporting

lessons.yaml
=> Calling Methods German translation

lessons.yaml
=> charcters -> characters

lessons.yaml
=> Update German translation Export

lessons.yaml
=> Lesson 3 German pub terminology

lessons.yaml
I felt like arrays really should be talked about earlier, and also some elaboration on primitive data types.
=> Need a page on arrays

lessons.yaml
Traslation wasn't detected because of the extra spaces
=> Fix the "memory" page structure

lessons.yaml
I translated all of chapter 1 to french
=> French translation of chap1

lessons.yaml
=> Updated loop break description in German

lessons.yaml
=> Updated mutable page in German

lessons.yaml
=> Translated untranslated in German

lessons.yaml
I finished the french translation of chapter 3
=> Translation french end of chap3

lessons.yaml
A few mistakes corrected and some changes to make it read better (IMO).
Feel free to challenge me on my changes.
=> [EN] Memory regions - Update grammar

lessons.yaml
Finished the french version of chapter 4
=> Translation french chap4

lessons.yaml
Changes from
https://github.com/richardanaya/tour_of_rust/pull/87/files
=> [FR] Minor changes on memory

lessons.yaml
Shouldn't the section 'Ugly Option/Error Handling' be 'Ugly Option/Result Error Handling' instead?
=> Spanish translations for Chapter 4

lessons.yaml
Translation of chapter 5. Still a few pages to do.
That was not an easy part, there are a lot of english terms.
:)
=> French chap5 part 1

lessons.yaml
I corrected some grammar and orthograph issues in the French translation.
=> [Lessons FR] Grammar and orthograph correction

lessons.yaml
=> [FR] Translation chap5 end

lessons.yaml
I corrected some typos and other grammar issues on chapter 5.
=> [FR] Corrections chapter 5

lessons.yaml
=> typo on string slice

lessons.yaml
=> [FR] translation to french chap6 end

wasm.yaml
I started Tour of WebAssembly!
=> [FR] WASM translation of introduction

lessons.yaml
I corrected some typos and other grammar issues for Chapter 6 in French.
=> [FR] Correction of Chapter 6

lessons.yaml
Couple fixes from reading over the last chapter. Very cool stuff :-)
=> [EN] Couple typos/grammar fixes

wasm.yaml
=> [FR] WASM translation chap2 beginning

wasm.yaml
=> [FR] translation chap2 done

lessons.yaml
Finished chapter 7 of tour of rust.
=> [FR] rust translation chap7 end

lessons.yaml
started chapter 8 of tour of rust
=> [FR] rust translation chap 8 beginning

lessons.yaml
Finished chapter 8 of Tour of Rust
=> [FR] rust end of chapter 8

lessons.yaml
I have quickly read the previous chapters and made some changes.
I added corrections from https://github.com/richardanaya/tour_of_rust/pull/150 which were not merged.
I translated the "The End" page.
=> [FR] small changes after proofreading

lessons.yaml
I have translated the Chapter 1 into Japanese.
=> [JA] Rust translation chap1 done

wasm.yaml
I'm from Spain, and I just saw this project, so I thought contributing could be a great idea!
=> Partial translation into Spanish :)

wasm.yaml
I finished chapter 3 of tour of WebAssembly!
=> [FR] wasm translation chapter 3 end

lessons.yaml
from https://github.com/richardanaya/tour_of_rust/issues/169
=> [FR/ES] translation of common_words

lessons.yaml
Just a few changes to the english version
=> [EN] rust minor changes to chap9

lessons.yaml
Currently, they are not formatted and it is hard to read and also see how many and resources there are. Interestingly, Japanese version already had them formatted as a bullet list.
=> Format resources in 'Chapter 1 - Conclusion' as a list

README.md
I'm a big fan of explanatory READMEs to lower the bar of participation. What would you think of such a section on how to run the site locally? 🙃
=> Add explanation in README

README.md
=> Adding Raminos

lessons.yaml
This is a very large pull requests with many different changes. Sorry about that. I can split it up if needed.
Feel free to comment on any of them, I just committed everything I found while reading through.
=> Fix various typos and awkward phrasing

lessons.yaml
Mostly periods at the end of lines.
Not sure if all of these are wanted. Feel free to comment or edit.
Will probably conflict with #194 or #195...
=> Make punctuation more consistent

lessons.yaml
This is a really small commit.
But I hope this will be a trigger to many contribution from Rust Community in Japan.
=> added Japanese Translation on final chapter

lessons.yaml
common_words
pages
Chapter 1  - The Basic,
Rust Playground
=> Korean Translate 001

lessons.yaml
Here part of chapter four in German translation
=> Add German translation for the beginning of the fourth chapter

lessons.yaml
=> Fix typo in english text

lessons.yaml
Hey,
I started making a translation, I currently have it done from the beginning to where you discuss for loops. I hope it's on par with what you expect.
I have a question too, a lot of characters in my language don't really render well using the fonts you use. Is there any sort of easy fix to this issue? Here's an image that showcases this:
Ű and Ő look really out of place.
Have a nice day!
=> Hungarian translation

lessons.yaml
This one has everything till the end of Chapter 3.
=> Hungarian translation 2nd batch

lessons/hu/chapter_4.yaml
I like the new system, however, I'd like to ask for a bit of clarification. How should we exactly format these yaml files? When i started editing chapter 4, I saw a lot of seemingly senseless line-breaks in the original version. I ultimately chose to go with line-breaks only where I actually want them to happen.
Anyway, pull introduces Chapter 4 in Hungarian.
=> Chapter 4 in Hungarian

lessons/de/chapter_9.yaml
i added two new translations for DE
=> Chapter9 - DE translations

lessons/de/chapter_0.yaml
=> Update German translation

lessons/de/chapter_1.yaml
fix the spelling for "zu Nutze" according to the recommandation by [duden spelling dictionary](https://www.duden.de/rechtschreibung/zunutze)
=> small spelling fix

lessons/zh-cn/chapter_5.yaml
Signed-off-by: JmPotato <ghzpotato@gmail.com>
=> [ZH-CN] Translate Chapter-5 into Simplified Chinese

wasm/ja/chapter_2.yaml
I learned a lot from this chapher. 📝 
Refs #201
=> Translate wasm-2 into Japanese

lessons/de/chapter_9.yaml
finish translation of chapter 09 for german language
=> finish german translation for chapter 09

wasm/ja/chapter_3.yaml
=> Translate wasm-3 into Japanese

README.md, lessons/README.md, lessons/zh-tw/chapter_1.yaml
- Add Traditional Chinese translation to lesson
- add chapter_1
- updated `lessons/README.md` zh-tw translation completeness
- Updated `README.md`
- add myself as zh-tw translation contributors.
=> Add Traditional Chinese translation to lesson chapter_1

lessons/fa/chapter_0.yaml
Upon trying to run the site on my local machine I stumble upon the error which prevents me to compile the project,
The actual problem is that the particular line has bad indentation, missing 1 space character, this pr fix those issue.
=> Fix - Bad Farsi Indentation

lessons/pt-br/chapter_6.yaml
I'll add more chapters to this PR if possible!
=> Translate Chapter 6 into Brazilian Portuguese

lessons/README.md, lessons/id/chapter_2.yaml
By the way I haven't put the link for bahasa Indonesia in 00_*.html, do you want me to add the text or should we wait until the next release (if there's such a thing)?
=> Add bahasa Indonesia translation for chapter 2

lessons/ko/chapter_0.yaml, lessons/ko/chapter_1.yaml, lessons/ko/chapter_10.yaml, lessons/ko/chapter_2.yaml, lessons/ko/chapter_3.yaml, lessons/ko/chapter_4.yaml, lessons/ko/common_words.yaml
Hi, I added/modified some files for Korean.
=> (KO) Add/improve translations for chapter 0, 1, 2, 3, 4, and 10

lessons/hu/chapter_3.yaml, lessons/hu/chapter_7.yaml
They are annoying to revert when my editor is set up to trim them on save.
=> [HU] Trim trailing whitespaces

lessons/hu/chapter_1.yaml
This PR aims to make the hungarian translation a bit more friendly at places.
Also removes a single line of english text.
=> [HU] Minor cleanup in chapter 1

lessons/ko/chapter_5.yaml, lessons/ko/chapter_6.yaml, lessons/ko/chapter_9.yaml
Hi, here are three more chapters for KO :-)
=> (KO) Add translations for chapter 5, 6, and 9

lessons/ja/chapter_6.yaml
https://github.com/richardanaya/tour_of_rust/issues/201#issuecomment-668999823
Good day!
I've translated 60_ja.html into Japanese!
=> Translate 60_ja into Japanese

lessons/README.md, lessons/ko/chapter_7.yaml
Hi, here goes the chapter 7 :-)
I also edited the lessons/README.md file.
=> (KO) Add translations for chapter 7

lessons/en/chapter_3.yaml
Make "Ferris" on the left be the same as "Ferris" in the code on the right.
=> String "Ferris" capitalized

lessons/ja/chapter_6.yaml
I've translated 61_ja and 62_ja into Japanese!
=> Translate 61_ja and 62_ja into Japanese

lessons/hu/chapter_0.yaml, lessons/hu/chapter_1.yaml, lessons/hu/chapter_2.yaml, lessons/hu/chapter_3.yaml, lessons/hu/chapter_4.yaml, lessons/hu/chapter_5.yaml, lessons/hu/chapter_6.yaml, lessons/hu/chapter_7.yaml
This PR is a work in progress aimed to make the Hungarian translation more friendly and less verbatim. While not nearly ready, it's public so that others may review the changes.
=> [HU] Clean up

lessons/README.md, lessons/ko/chapter_7.yaml, lessons/ko/chapter_8.yaml
Hi, here's the last one, the chapter 8.
I was in a little hurry with some chapters,
so I'll create pull requests anytime when I find any typo or improvement :-)
=> (KO) Add translations for chapter 8

lessons/hu/chapter_0.yaml, lessons/hu/chapter_1.yaml, lessons/hu/chapter_2.yaml, lessons/hu/chapter_3.yaml, lessons/hu/chapter_4.yaml, lessons/hu/chapter_5.yaml, lessons/hu/chapter_6.yaml, lessons/hu/chapter_7.yaml
This fixes most of the formatting I messed up when reflowing the text
=> [HU] Use included newlines

README.md, lessons/README.md
Also apply a miniscule cleanup to the main README
=> Remove duplicate es line from lessons README

lessons/ja/chapter_6.yaml
I've translated chapter 6-3 and 6-4 into Japanese!
=> Translate chapter 6-3 and 6-4 into Japanese

README.md, lessons/es/chapter_0.yaml, lessons/es/chapter_1.yaml, lessons/es/chapter_2.yaml, lessons/es/chapter_5.yaml, lessons/es/chapter_6.yaml, lessons/es/chapter_7.yaml, lessons/es/chapter_8.yaml, lessons/es/chapter_9.yaml, lessons/es/common_words.yaml
=> Spanish Translations for Chapters 5, 6, 7, 8, and 9.

lessons/ja/chapter_6.yaml
I've translated chapter 6-5, 6-6, 6-9 and 7-1 into Japanese!
=> Translate chapter 6-5, 6-6, 6-9 and 7-1 into Japanese

lessons/README.md, lessons/de/chapter_0.yaml, lessons/en/chapter_0.yaml, lessons/es/chapter_0.yaml, lessons/fa/chapter_0.yaml, lessons/fr/chapter_0.yaml, lessons/hu/chapter_0.yaml, lessons/id/chapter_0.yaml, lessons/ie/chapter_0.yaml, lessons/ja/chapter_0.yaml, lessons/ko/chapter_0.yaml, lessons/pl/chapter_0.yaml, lessons/pl/chapter_1.yaml, lessons/pl/chapter_10.yaml, lessons/pl/chapter_2.yaml, lessons/pl/chapter_3.yaml, lessons/pl/chapter_4.yaml, lessons/pl/chapter_5.yaml, lessons/pl/chapter_6.yaml, lessons/pl/chapter_7.yaml, lessons/pl/chapter_8.yaml, lessons/pl/chapter_9.yaml, lessons/pl/common_words.yaml, lessons/pt-br/chapter_0.yaml, lessons/ru/chapter_0.yaml, lessons/zh-cn/chapter_0.yaml, lessons/zh-tw/chapter_0.yaml
Here are the first 3 chapters translated to Polish. I intend to work on the remaining chapters and the playground examples (comments and whatnot) as well. Here's what I've got so far.
Cheers!
=> Start work on pl translation

README.md
Signed-off-by: SeongJae Park <sj38.park@gmail.com>
=> README: Fix a typo: Duplicated 'appropriate'

lessons/tr/chapter_4.yaml
Translation of part 4 completed
=> chapter_4.yaml

lessons/th/chapter_0.yaml
And removed unnecessary Thai link 'cause it's already navigate to it.
=> Fixed missing English link in language selection.

README.md, lessons/README.md, lessons/zh-tw/chapter_2.yaml
Great project! I gave up when I wanted to learn Rust by official document at first until I found this tour.
I add chapter 2 of zh-tw. Some keywords are so common and I didn't translate them.
I'll try to keep translating 1 or a half chapter once a week.
=> Add chapter 2 of zh-tw

lessons/zh-cn/chapter_7.yaml
=> Fix chinese typo

lessons/en/chapter_2.yaml
With an output, a learner can actually test the behaviour.
=> chore: added println for the while lesson

lessons/en/chapter_7.yaml
See https://en.wikipedia.org/wiki/Polymorphism_(computer_science)#History
=> Fix the definition of OOP polymorphism

lessons/en/chapter_8.yaml
=> feat(chapter_8): added 2 playground code samples

lessons/de/chapter_1.yaml, lessons/en/chapter_1.yaml
=> chore: improved function lesson

README.md, lessons/en/chapter_0.yaml, lessons/it/chapter_0.yaml, lessons/it/chapter_1.yaml, lessons/it/common_words.yaml, yarn.lock
Hello, I started by translating the first chapter to Italian. Let me know what you think about
=> italian translation - first chapter

lessons/en/chapter_5.yaml, lessons/fa/chapter_5.yaml, lessons/gr/chapter_5.yaml, lessons/hu/chapter_5.yaml, lessons/ie/chapter_5.yaml, lessons/ja/chapter_5.yaml, lessons/ko/chapter_5.yaml, lessons/pl/chapter_5.yaml, lessons/ru/chapter_5.yaml, lessons/th/chapter_5.yaml, lessons/tr/chapter_5.yaml, lessons/zh-tw/chapter_5.yaml
Thank you for your great tour!
I found a minor typo in the full form of RAII, so I patched it.
=> Fix typo of RAII

lessons/ja/chapter_6.yaml
translate the rest of chapter6 into Japanese
refs #201
=> translate 67_ja into Japanese

lessons/README.md, lessons/fi/chapter_0.yaml, lessons/fi/chapter_1.yaml, lessons/fi/common_words.yaml
Chapters 0 and 1 for the Finnish translation
=> Initial FI translation

lessons/fr/chapter_0.yaml, lessons/fr/chapter_1.yaml, lessons/fr/chapter_2.yaml
Hi, 
I found some typos reading the french translation, so this PR aims to provide corrections on the chapter 0, 1 and 2 for the french language.
Let me now if I forgot something
=> [FR] - Correct typos on chapter 0, 1, 2

docs/tour.css
Fixes #424 
Before:
https://www.loom.com/share/f5cff5f1c9ef45d09ac409e499a226e0
After:
https://www.loom.com/share/bf5b3697e2684b69bbf04ee6797d90cc
=> Make code portion larger

lessons/ja/chapter_7.yaml
Translated Chapter 7 in Japanese.
=> [JA] - Chapter 7

lessons/de/chapter_0.yaml, lessons/en/chapter_0.yaml, lessons/es/chapter_0.yaml, lessons/fa/chapter_0.yaml, lessons/fi/chapter_0.yaml, lessons/fr/chapter_0.yaml, lessons/gr/chapter_0.yaml, lessons/hu/chapter_0.yaml, lessons/id/chapter_0.yaml, lessons/it/chapter_0.yaml, lessons/ja/chapter_0.yaml, lessons/ko/chapter_0.yaml, lessons/pl/chapter_0.yaml, lessons/pt-br/chapter_0.yaml, lessons/ro/chapter_0.yaml, lessons/ro/common_words.yaml, lessons/ru/chapter_0.yaml, lessons/th/chapter_0.yaml, lessons/tr/chapter_0.yaml, lessons/ua/chapter_0.yaml, lessons/vi/chapter_0.yaml, lessons/zh-cn/chapter_0.yaml, lessons/zh-tw/chapter_0.yaml
This only adds chapter 0 and the rest is work in progress.
[https://github.com/UPB-CS-OpenSourceUpstream/tour_of_rust/pull/2](https://github.com/UPB-CS-OpenSourceUpstream/tour_of_rust/pull/2)
=> Chapter 0 translation in romanian 🇷🇴

lessons/ro/chapter_5.yaml
I translated Chapter 5 in Romanian, including code snippets.
This PR was also discussed at:
https://github.com/UPB-CS-OpenSourceUpstream/tour_of_rust/pull/4
=> Romanian translation for Chapter 5 🇷🇴

lessons/ro/chapter_9.yaml
This pull request adds a Romanian translation for Chapter 9.
=> Chapter 9 Romanian Translation 🇷🇴

lessons/ro/chapter_7.yaml
I translated Chapter 7 in Romanian, including code snippets.
This PR was also discussed at:
https://github.com/UPB-CS-OpenSourceUpstream/tour_of_rust/pull/6
=> Translated Chapter 7 of the Rust tour in Romanian 🇷🇴

lessons/ro/chapter_6.yaml
I translated Chapter 6 in Romanian, including code snippets.
This PR was also discussed at:
https://github.com/UPB-CS-OpenSourceUpstream/tour_of_rust/pull/7
=> Translated Chapter 6 of the Rust tour in Romanian 🇷🇴

lessons/fi/chapter_2.yaml
Translated Chapter 2 in Finnish.
=> Chapter 2 Finnish Translation 🇫🇮

lessons/README.md
README has been updated to include (currently accepted) Romanian chapters.
=> Update README progress table

lessons/en/chapter_6.yaml, lessons/es/chapter_6.yaml, lessons/fa/chapter_6.yaml, lessons/fr/chapter_6.yaml, lessons/hu/chapter_6.yaml, lessons/ie/chapter_6.yaml, lessons/pl/chapter_6.yaml, lessons/ru/chapter_6.yaml, lessons/th/chapter_6.yaml, lessons/vi/chapter_6.yaml, lessons/zh-tw/chapter_6.yaml
The author of the haiku written in the document (chapter_6.yaml) that is not in Japanese was incorrect. Tachibana Hokushi(立花北枝) is not Katsushika Hokusai.I have corrected it.
=> Corrected the author name of the haiku

lessons/ro/chapter_6.yaml
I fixed typos and other errors in the Romanian translation of Chapter 6.
This pull request was discussed here:
https://github.com/UPB-CS-OpenSourceUpstream/tour_of_rust/pull/11
=> Updated translation of Chapter 6 in Romanian 🇷🇴

lessons/ro/chapter_7.yaml, yarn.lock
"I have corrected some typos and grammatical errors.
=> updated romanian translation of chapter 7

wasm/en/chapter_0.yaml, wasm/en_c/chapter_0.yaml, wasm/es/chapter_0.yaml, wasm/fr/chapter_0.yaml, wasm/fr_c/chapter_0.yaml, wasm/ie/chapter_0.yaml, wasm/ja/chapter_0.yaml, wasm/pt-br/chapter_0.yaml, wasm/ro/chapter_0.yaml, wasm/ro/chapter_1.yaml, wasm/ro/chapter_2.yaml, wasm/ro/chapter_3.yaml, wasm/ro/common_words.yaml
Translated chapters 0, 1, 2 and 3 of the WebAssembly tutorial to Romanian.
=> Translated WebAssembly tutorial to Romanian

lessons/al/chapter_0.yaml, lessons/al/chapter_1.yaml, lessons/al/chapter_2.yaml, lessons/al/chapter_3.yaml, lessons/al/common_words.yaml
I added the albanian language for cahpters 0,1,2 and 3
=> Albanian Language

lessons/al/chapter_0.yaml, lessons/al/chapter_1.yaml, lessons/al/chapter_2.yaml, lessons/al/chapter_3.yaml, lessons/al/common_words.yaml
Reverts richardanaya/tour_of_rust#526
=> Revert "Revert "Albanian Language""
