- lessons.yaml
An english phrase was still here in the spanish translation
> Deleted a english phrase from the spanish version

- lessons.yaml
The method name for length in std::string::String is len(), not length().
> Fixed a typo in method name: changed length() to len()

- lessons.yaml
I feel like it's confusing to the reader that one of the match arm explicitly returns while the other one doesn't
> Graceful Error Handling - Update code example

- lessons.yaml
Mentioning `&Trait` might seem weird as it can't be really used like that as the `dyn` keyword is required to highlight the dynamic dispatch.
> Docs:  `&Trait` as `&dyn Trait` for consistency.

- wasm.yaml
Corrected Grammar, typos and other issues on the French translation of WASM tour.
Note : Github's editor has added a newline at the end of the file.
> [FR] Correction of WASM Chapter 1 & beginning of 2

- lessons.yaml
Since "let's" is a contradiction of "let us", saying "let's us" is a bit like saying "let us us". Changed all instances to "lets us".
> Replace instances of "let's us" with "lets us"

- lessons.yaml
I feel it makes more sense if we split the Module Hierarchy page and create a Creating Modules page.
I also made some small changes in the phrasing.
Can you check if you like it?
I updated the interlingue version but it still in English and need proper translation.
> [EN] split Module Hierarchy page

- lessons.yaml
"Tour zu Rust" implies a tour that leads towards Rust. "Tour durch Rust" is a tour through something as is a tour _through_ a museum.
> Update German translation

- lessons.yaml
Hey Richard,
thanks for this wonderful project! I enjoy it tremendously and would love to contribute.
In this PR I propose to add the `==` operator to the list of operators in the control flow chapter. I added the operator to all languages. 
Additionally, I added the word 'relational' to English, German, French, Portuguese and Spanish (I checked with natives in Portuguese, French and Spanish and I'm a German native myself) since I thought it is nice to have correct naming (I know it is a bit picky and not necessary at all 😄 ). 
As I said I love the project and would be happy to contribute more (missing German translation in the Array chapter for example)!
> Add missing equal operator

- lessons.yaml
Remove ampersand in the call &creature.get_sound(), since get_sound() already returns
a reference. Changed in all (English and French) code examples.
See https://tourofrust.com/77_en.html, line 17 to view and test the effect with and without an ampersand.
> Remove confusing reference

- lessons.yaml
Inherit**e**nce should be spelled Inherit**a**nce.
> inheritance spell correction

- lessons.yaml
Since I was already at it I also moved all the older html occurrences in the German part to markdown. On the way I changed a few typos and grammatical errors.
> Turn German html into markdown

- lessons.yaml
As promised the Arrays chapter translation 😊 !
Is the html in part of the translations a remnant of older versions or does it serve a specific reason? Otherwise I would fix that for German.
> Add German translation for arrays chapter

- wasm.yaml
Thank you for nice project 😉 
I've just translated `wasm` section 1 into Japanese.
> Add japanese translation for wasm-1

- lessons/ja/chapter_3.yaml
I found a typo in `ja/chapter_3.yaml`. Fixed it.
> [JA] Fix typo

- wasm/en/chapter_0.yaml
- wasm/en_c/chapter_0.yaml
- wasm/es/chapter_0.yaml
- wasm/fr/chapter_0.yaml
- wasm/fr_c/chapter_0.yaml
- wasm/ie/chapter_0.yaml
- wasm/ja/chapter_0.yaml
- wasm/pt-br/chapter_0.yaml
In `wasm/${lang}/chapter_0.yml`, links for other languages should point to `00_${lang}.html`.
But for now it points to `index_${lang}.html` and becomes 404. 😿 
This PR fixes it and also follows Tour of Rust's manner(which makes current lang not to be listed).
> [wasm] Fix broken top links

- lessons/en/chapter_1.yaml
- lessons/hu/chapter_1.yaml
Technically speaking, the terms "positive" and "negative" integers exclude zero. While nonnegative is a bit less friendly, it is the correct term to describe unsigned integers.
> Some love for 0

- lessons/en/chapter_8.yaml
Wasn't sure exactly if this was meant to be "copied or passed around" or simply "passed around", so I went with the longer one.
> [EN] Try to fix a missing word

- lessons/es/chapter_1.yaml
There was a little typo of the markdown on the Spanish version
https://tourofrust.com/05_es.html
> Fix Markdown of the rust data types

- lessons/zh-tw/chapter_0.yaml
> Fix English chapter 0 link in Traditional Chinese page

- lessons/README.md
After #370, I took a better look into the missing  Brazilian Portuguese translation chapters.
|Chapter| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
|------|---|---|---|---|---|---|---|---|---|---|----|
|pt-br | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ |   |   |   | ✓  |
I checked the chapters (I'm also a native pt-br speaker :D), and it looks pretty complete to me (and very well translated! All thanks to @Denstone).
@Denstone, can you confirm if this is correct?
> Marking all portuguese translations as complete

- lessons/en/chapter_2.yaml
I'm not sure if it's intentional or not, but it's probably confusing if there is 2x if/else in the title.
> chore: remove double if/else in title

- lessons/en/chapter_1.yaml
Since some programming languages only know dynamic arrays (e. g. JS or PHP), I think it's important to highlight the distinction.
> chore: add hint about dynamic arrays

- lessons/en/chapter_1.yaml
Since the description uses the 2 different words "parameters" and "arguments", it's useful to give a hint for that.
> chore: add hint for function parameters and arguments

- lessons/de/chapter_1.yaml
Hello. I found a tiny typo in the German translation and would like to correct it. Thanks!
> fix uint -> usize in german translation

- docs/tour.css
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
I was going through the rust tour and found that the underscores(`_`) are not visible in the code blocks, that caused some confusion for me in some places. I found a quick fix to add a little padding to the code blocks which makes the underscores visible. I have attached the screenshots for reference.
-  Before
- After
> Added padding in code block to make '_' visible

- lessons/pt-br/chapter_1.yaml
- lessons/pt-br/chapter_4.yaml
This merge:
- Fixes some typos and grammar issues
- Renames ***Matrizes*** to ***Arrays***, it is better to leave this untranslated.
- In brazilian portuguese, and in the programming context, the word ***matrizes*** is commonly referred only to two-dimensional arrays and up.
- The widely used MDN documentation (for JS) also choses to [not translate the term](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array).
> Fix: issues in chapters 1 and 4 of the pt_br translation

- lessons/ro/chapter_1.yaml
- lessons/ro/chapter_2.yaml
- lessons/ro/chapter_3.yaml
- lessons/ro/chapter_4.yaml
I translated Chapters 1-4 in Romanian, including code snippets.
This PR was also discussed at:
https://github.com/UPB-CS-OpenSourceUpstream/tour_of_rust/pull/3
> Romanian translation for Chapters 1-4 🇷🇴

- lessons/de/chapter_2.yaml
Change in the code example (2nd print statement) from     
```
fn main() {
print!("0..5 :");
for x in 0..5 {
print!(" {}", x);
}
print!("\n0..5=:");
for x in 0..=5 {
print!(" {}", x);
}
}
```
to
```
fn main() {
print!("0..5 :");
for x in 0..5 {
print!(" {}", x);
}
print!("\n0..=5 :");
for x in 0..=5 {
print!(" {}", x);
}
}
```
> Fixes typo in German "for" code example.

- lessons/en/chapter_1.yaml
- lessons/ro/chapter_1.yaml
In chapter 1 of Tour of Rust, the char type is not mentioned in the Basic Types lesson. This issue has also been noticed in the following open issue: https://github.com/richardanaya/tour_of_rust/issues/420
The changes include adding the text explanation of `char` type use and updating the code example for both English and Romanian versions.
> Added `char` explanation and code example

- lessons/vi/chapter_5.yaml
The code in Chapter 5 is currently not executable, so I have created this PR to fix that.
Old code:
```rs
fn main() {
let mut foo = 42;
let f = &mut foo;
let bar = *f; // nhận một bản sao của quyền sở hữu
```
New code
```rs
fn main() {
let mut foo = 42;
let f = &mut foo;
let bar = *f; // nhận một bản sao của quyền sở hữu
println!("{}", bar);
println!("{}", foo);
}
```
> Update chapter_5.yaml | Fix Dereferencing code in Vietnamese
